# About
A collection of python scripts to do various sample curation. The program will be run out of main as the intended starting script. Each included script can be run by itself but will be built to be called from main. For now, wired into main are the below functions.

# Scripts
## Splitter
Splitter is designed to split audio samples from an exported WAV file from a DAW. I create a scale from C1 to C7 with a fixed tempo of 60 and a 1 bar sample with a 1 bar of silence before the next sample. This will work with 2 bars, 4 bars...etc. Splitter uses an array to label the samples from C1 to C7. Most of Ableton's midi sounds start at C1 and progress so, for larger instruments it was easier to create a massive scale from C1 to C7, export and then split. The splitter will only generate a sound file if it contains audio so doing a large export from your DAW does not necessarily mean you'll have a bunch of clean up.

## Silencer
This plugin is meant to trim the ends of the the audio files generated by Splitter. Because the audio files are WAV files and some instruments, like the 404 do not play well with FLAC, I trim after I split them.